### ISSUE TITLE
detect_type fails when Dir.pwd doesn't contain trailing slash

### ISSUE THREAD

**Issue by exoemay** [boltops-tools/rspec-terraspace#9]
Hey, I've encountered an issue with an easy fix.

In `project.rb`, the `detect_type` function will fail if `Dir.pwd` does not contain a trailing slash (as is the case on my system). A simple ? after the slash in the regex fixes this issue.

```ruby
md = dir.match(%r{app/(stacks|modules)/(.*)?/?})
```

If you want I can create a PR for this as well, unless you prefer a different solution.

**Comment by tongueroo** [comment]
The regexp works. Send the PR when you get the chance.

**Comment by exoemay** [comment]
PR is ready :)
